apiVersion: v1
kind: Service
metadata:
  name: discourse
  namespace: discourse
  labels:
    app: discourse
    component: main
spec:
  ports:
    - port: 3000
      protocol: TCP
      # name: postgresql
  selector:
    app: discourse
    component: main
