apiVersion: v1
kind: Service
metadata:
  name: ingress-controller-defb
    #^ must be no more than 24 characters
  namespace: ingress
  labels:
    app: ingress-controller
    component: defaultbackend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: ingress-controller
    component: defaultbackend
