apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: discourse
  labels:
    app: discourse
    component: postgres
spec:
  ports:
    - port: 5432
      protocol: TCP
      name: postgresql
  selector:
    app: discourse
    component: postgres
