apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: discourse
  labels:
    app: discourse
    component: redis
spec:
  ports:
    - port: 6379
      protocol: TCP
      # name: postgresql
  selector:
    app: discourse
    component: redis
